Volodin Evgeniy. Lab №3 Option №1.
NN-complr-tech/llvm-nnsu-2024 pull request #108
Opened 2024-04-23 06:40 UTC by evldn

In this lab, a pass was implemented that replaces the argument-dependent mul and add instructions with one - muladd.
**The source code:**
``` C++
#include <immintrin.h>

__m128d simple_test(__m128d a, __m128d b, __m128d c, __m128d d) {
	__m128d temp = a * b;
	d = temp + c;
	return d;
}
```
**LLVM MIR code before applying the pass:**
``` MIR
body:             |
  bb.0.entry:
    liveins: $xmm0, $xmm1, $xmm2
  
    renamable $xmm0 = nofpexcept MULPDrr killed renamable $xmm0, killed renamable $xmm1, implicit $mxcsr
    renamable $xmm0 = nofpexcept ADDPDrr killed renamable $xmm0, killed renamable $xmm2, implicit $mxcsr
    RET64 $xmm0
```
**LLVM MIR code after applying the pass:**
``` MIR
body:             |
  bb.0.entry:
    liveins: $xmm0, $xmm1, $xmm2
  
    $xmm0 = VFMADD213PDr $xmm0, $xmm1, $xmm2, implicit $mxcsr
    RET64 $xmm0
```

2024-04-24 08:18 UTC, m-ly4 requested changes

2024-04-24 08:18 UTC, m-ly4 commented on llvm/lib/Target/X86/CMakeLists.txt
> +  X86VolodinEMulAddPass.cpp
Please rewrite it as shared lib plugin.

2024-04-24 08:18 UTC, m-ly4 commented on llvm/lib/Target/X86/X86VolodinEMulAddPass.cpp
> +    return true;
```suggestion
  return (result != end(MIvector));
```

2024-04-24 08:18 UTC, m-ly4 commented on llvm/lib/Target/X86/X86VolodinEMulAddPass.cpp
> +      if (iterator->getOpcode() == X86::MULPDrr) {
```suggestion
      if (iterator->getOpcode() != X86::MULPDrr) {
        continue;
      }
```

2024-04-24 08:18 UTC, m-ly4 commented on llvm/test/lab3/test_muladd.mir
> +
Please add also:
```
# __m128d another_test(__m128d a, __m128d b, __m128d c, __m128d d) {
# 	__m128d t = a * b;
# 	__m128d t2 = c * d;
# 	t2 = t + t2;
# 	t = t + c;
# 	return t * t2;
# }
```

2024-04-26 00:24 UTC, evldn commented
1. I rewrote pass as shared lib plugin.
2. I added the test you suggested, which was performed incorrectly on the old version of the pass. I fixed this by adding additional checks to the pass that track the mutability of operands between the mul and add instructions.

2024-04-26 04:15 UTC, m-ly4 approved these changes

2024-04-26 04:16 UTC, merged