Sharapov Georgiy. Lab 4. Option 1.
NN-complr-tech/llvm-nnsu-2024 pull request #144
Opened 2024-05-15 17:44 UTC by nol0n

Implemented mlir pass that breaks arith.ceildivui and arith.ceildivsi operations into calculation following the rule: ceildiv(a, b) = (a + b - 1) / b.

2024-05-17 16:14 UTC, aobolensk requested changes

2024-05-17 16:14 UTC, aobolensk commented on mlir/test/Transforms/lab4/sharapov_georgiy/test.mlir
> +module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<!llvm.ptr<270>, dense<32> : vector<4xi32>>, #dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi
These options may be omitted here.
```suggestion
module {
```

2024-05-17 16:14 UTC, aobolensk commented on mlir/test/CMakeLists.txt
> +  set(MLIR_TEST_DEPENDS ${MLIR_TEST_DEPENDS}
```suggestion
set(MLIR_TEST_DEPENDS ${MLIR_TEST_DEPENDS}
```

2024-05-17 16:14 UTC, aobolensk commented on mlir/test/Transforms/lab4/sharapov_georgiy/test.mlir
> +    // CHECK-NEXT: %2 = arith.divsi %1, %arg1 : i32
Do not rely on specific numbers in IR values:
```suggestion
    // CHECK-NEXT: %c1_i32 = arith.constant 1 : i32
    // CHECK-NEXT: %[[add:.*]] = arith.addi %arg0, %arg1 : i32
    // CHECK-NEXT: %[[sub:.*]] = arith.subi %[[add]], %c1_i32 : i32
    // CHECK-NEXT: %[[div:.*]] = arith.divsi %[[sub]], %arg1 : i32
```

2024-05-18 08:25 UTC, aobolensk approved these changes

2024-05-18 08:38 UTC, m-ly4 requested changes

2024-05-18 08:38 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/sharapov_georgiy/sCeilDiv.cpp
> +    Value div = builder.create<arith::DivUIOp>(loc, sub, b);
The difference between methods is only in one instruction. Would be nice to write one method with selections depending on input type to reduce code duplication.

2024-05-19 04:20 UTC, m-ly4 requested changes

2024-05-19 04:20 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/sharapov_georgiy/sCeilDiv.cpp
> +        replaceCeilDiv(ceilDivSI, OpType::SignedOp);
```suggestion
      if (isa<arith::CeilDivUIOp, arith::CeilDivSIOp>(op)) {
        replaceCeilDiv(dyn_cast<arith::IntBinaryOp>(op));
```

2024-05-19 04:20 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/sharapov_georgiy/sCeilDiv.cpp
> +  void replaceCeilDiv(CeilDivOpType op, OpType type) {
```suggestion
  void replaceCeilDiv(arith::IntBinaryOp op) {
```

2024-05-19 04:20 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/sharapov_georgiy/sCeilDiv.cpp
> +    if (type == OpType::SignedOp) {
```suggestion
    if (isa<arith::CeilDivSIOp>(op)) {
```

2024-05-19 06:54 UTC, nol0n commented on mlir/lib/Transforms/lab4/sharapov_georgiy/sCeilDiv.cpp
> +        replaceCeilDiv(ceilDivSI, OpType::SignedOp);
Initially, I wanted to write something similar. But I didn’t know if these operations were an implementation of some appropriate interface ([arith ceildiv ref](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithceildivsi-arithceildivsiop)).

As far as I understand there are no such thing like BinaryOp or IntBinaryOp in arith dialect. And I can’t find anything similar that fits here.

```
error: no member named 'IntBinaryOp' in namespace 'mlir::arith'
                replaceCeilDiv(dyn_cast<arith::IntBinaryOp>(op));
                                        ~~~~~~~^
```

2024-05-19 15:45 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/sharapov_georgiy/sCeilDiv.cpp
> +        replaceCeilDiv(ceilDivSI, OpType::SignedOp);
Ok, I see. Nevermind.

2024-05-19 15:45 UTC, m-ly4 approved these changes

2024-05-19 15:46 UTC, merged