Kostin Artem. Lab #1. Var 3.
NN-complr-tech/llvm-nnsu-2024 pull request #15
Opened 2024-03-16 12:51 UTC by aartyomm

A plugin that issues a warning if it encounters a function whose name contains "deprecated".

2024-03-17 08:05 UTC, m-ly4 commented on clang/labs/lab1/kostin_artem/depr_plugin.cpp
> +    return true;
Could you please add an optional parameter that specifies case insensitive search in names?
For example, if plugin is executed without it, it searches for lowercase `deprecated` only.
If the plugin is executed with `-i` option then your current implementation.

2024-03-17 08:05 UTC, m-ly4 commented on clang/labs/lab1/kostin_artem/CMakeLists.txt
> +    set(LLVM_LINK_COMPONENTS
Please fix indentations in this file.

2024-03-17 08:19 UTC, m-ly4 requested changes

2024-03-17 08:19 UTC, m-ly4 commented on clang/labs/lab1/kostin_artem/depr_plugin.cpp
> +  CustomNodeVisitor(ASTContext *_Context) { Context = _Context; }
Please fix clang-tidy warnings: https://github.com/NN-complr-tech/llvm-nnsu-2024/actions/runs/8308820779/job/22739468242?pr=15#step:6:485

2024-03-18 05:35 UTC, aobolensk approved these changes

2024-03-18 12:05 UTC, m-ly4 approved these changes

2024-03-18 16:25 UTC, aobolensk approved these changes

2024-03-18 16:25 UTC, merged