Borovkov Sergey. Lab 3. Option 1.
NN-complr-tech/llvm-nnsu-2024 pull request #155
Opened 2024-05-18 12:22 UTC by slx52

An optimization pass that replaces multiplication and addition operation with muladd instruction.

2024-05-18 14:20 UTC, m-ly4 requested changes

2024-05-18 14:20 UTC, m-ly4 commented on llvm/test/lab3/borovkov_sergey/test.mir
> +# __m128d muladd_test2(__m128d a, __m128d b, __m128d c) {
Please add the following test:
```
__m128d muladd_test7(__m128d a, __m128d b, __m128d c) {
  __m128d tmp = a * b;
  return tmp + tmp;
}
```

2024-05-30 09:52 UTC, slx52 commented on llvm/test/lab3/borovkov_sergey/test.mir
> +# __m128d muladd_test2(__m128d a, __m128d b, __m128d c) {
Done.

2024-05-30 16:44 UTC, m-ly4 approved these changes

2024-05-30 16:45 UTC, merged