Первая лабораторная, вариант 1, Бендюжко Татьяна
NN-complr-tech/llvm-nnsu-2024 pull request #16
Opened 2024-03-16 14:11 UTC by Tatiana567

2024-03-17 08:22 UTC, m-ly4 requested changes

2024-03-17 08:22 UTC, m-ly4 commented on clang/labs/lab1/bend_tatiana/PrintFunctionNames.cpp
> +#include "clang/Frontend/FrontendPluginRegistry.h"
Please fix clang-format suggestions: https://github.com/NN-complr-tech/llvm-nnsu-2024/actions/runs/8308358647/job/22738518905?pr=16#step:4:10

2024-03-17 08:22 UTC, m-ly4 commented on clang/labs/lab1/bend_tatiana/PrintFunctionNames.cpp
> +        void HandleTranslationUnit(ASTContext& context) override {
Please fix clang-tidy warnings: https://github.com/NN-complr-tech/llvm-nnsu-2024/actions/runs/8308358647/job/22738518824?pr=16#step:6:485

2024-03-17 08:22 UTC, m-ly4 commented on clang/labs/lab1/bend_tatiana/PrintFunctionNames.cpp
> +            return true;
Please add an option `help` and a test for it.

2024-03-17 08:24 UTC, m-ly4 commented on clang/test/lab1/bend_tatiana/cats.cpp
> +    int variable;
Please add a check for static fields.

2024-03-18 16:26 UTC, aobolensk approved these changes

2024-03-18 17:14 UTC, m-ly4 approved these changes

2024-03-18 17:19 UTC, merged