Lebedeva Ksenia Lab4 Var4
NN-complr-tech/llvm-nnsu-2024 pull request #166
Opened 2024-05-19 22:35 UTC by ks2k23

Write a pass that counts amount of times it was called by other functions in the module, attach this as an attribute to function (func.func) operation.

2024-05-20 15:50 UTC, aobolensk requested changes

2024-05-20 15:50 UTC, aobolensk commented on mlir/lib/Transforms/lab4/lebedeva_ksenia/LebedevaCallFuncCounter.cpp
> +      if (auto callOp = dyn_cast<LLVM::CallOp>(op)) {
Why not use walker that goes through `LLVM::CallOp` only?

2024-05-20 15:50 UTC, aobolensk commented on mlir/lib/Transforms/lab4/lebedeva_ksenia/LebedevaCallFuncCounter.cpp
> +      if (auto functionOp = dyn_cast<LLVM::LLVMFuncOp>(op)) {
Same here, no need to filter operations by yourself, LLVM can do that for you

2024-05-20 15:50 UTC, aobolensk commented on mlir/test/Transforms/lab4/lebedeva_ksenia/test.mlir
> +    // CHECK: attributes {"call-count" = 4
Please, match call count attribute along with function name

2024-05-21 01:36 UTC, aobolensk approved these changes

2024-05-21 02:09 UTC, m-ly4 requested changes

2024-05-21 02:09 UTC, m-ly4 commented on mlir/test/Transforms/lab4/lebedeva_ksenia/test.mlir
> +    %8 = llvm.zext %7 : i1 to i8
```suggestion
  llvm.func @extern_func(i32) -> i32
  // CHECK: llvm.func @extern_func
  // CHECK-SAME: attributes {"call-count" = 1 : i32
  llvm.func @_Z9function4ii(%arg0: i32 {llvm.noundef}, %arg1: i32 {llvm.noundef}) attributes {passthrough = ["mustprogress", "noinline", "nounwind", "optnone", ["uwtable", "2"], ["frame-pointer", "all"], ["min-legal-vector-width", "0"], ["no-trapping-math", "true"], ["stack-protector-buffer-size", "8"], ["target-cpu", "x86-64"], ["target-features", "+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87"], ["tune-cpu", "generic"]]} {
    // CHECK: llvm.func @_Z9function4ii
    // CHECK-SAME: attributes {"call-count" = 0 : i32
    %0 = llvm.mlir.constant(1 : i32) : i32
    %1 = llvm.alloca %0 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
    %2 = llvm.alloca %0 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
    %3 = llvm.alloca %0 x i8 {alignment = 1 : i64} : (i32) -> !llvm.ptr
    %4 = llvm.alloca %0 x i8 {alignment = 1 : i64} : (i32) -> !llvm.ptr
    %5 = llvm.alloca %0 x i32 {alignment = 4 : i64} : (i32) -> !llvm.ptr
    llvm.store %arg0, %1 {alignment = 4 : i64} : i32, !llvm.ptr
    llvm.store %arg1, %2 {alignment = 4 : i64} : i32, !llvm.ptr
    %6 = llvm.load %1 {alignment = 4 : i64} : !llvm.ptr -> i32
    %7 = llvm.call @_Z9function1i(%6) : (i32) -> i1
    %8 = llvm.zext %7 : i1 to i8
    %9 = llvm.call @extern_func(%6) : (i32) -> i32
```

2024-05-22 02:19 UTC, m-ly4 approved these changes

2024-05-22 02:19 UTC, merged