Bonyuk Peter. Lab 4. Option 2.
NN-complr-tech/llvm-nnsu-2024 pull request #171
Opened 2024-05-20 18:50 UTC by PetrBonyuk

2024-05-21 01:40 UTC, aobolensk requested changes

2024-05-21 01:40 UTC, aobolensk commented on mlir/lib/Transforms/lab4/bonyuk_peter/BonyukFusedMultiplyAddPass.cpp
> +      if (auto AddOperation = dyn_cast<LLVM::FAddOp>(operation)) {
No need to walk through all operations, you can filter them by type in the walker itself

2024-05-21 01:42 UTC, aobolensk requested changes

2024-05-21 01:42 UTC, aobolensk commented on mlir/test/Transforms/lab4/bonyuk_peter/test.mlir
> +module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<f80, dense<128> : vector<2xi32>>, #dlti.dl_entry<i64, dense<64> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr<272>, dense<64> : vector<4xi3
```suggestion
module {
```

2024-05-21 01:42 UTC, aobolensk commented on mlir/test/Transforms/lab4/bonyuk_peter/test.mlir
> +    llvm.return
Please add check for inserted fma instruction

2024-05-21 01:52 UTC, m-ly4 requested changes

2024-05-21 01:52 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/bonyuk_peter/BonyukFusedMultiplyAddPass.cpp
> +    : public PassWrapper<BonyukFusedMultiplyAddPass, OperationPass<ModuleOp>> {
Please narrow down type of operation the pass is scheduled on.

2024-05-21 01:52 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/bonyuk_peter/BonyukFusedMultiplyAddPass.cpp
> +    module.walk([&](Operation *operation) {
```suggestion
    module.walk([](LLVM::FMulOp mulOp) {
```

2024-05-21 01:52 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/bonyuk_peter/BonyukFusedMultiplyAddPass.cpp
> +    if (FMAOperation.use_empty()) {
Typo?

2024-05-21 01:52 UTC, m-ly4 commented on mlir/test/Transforms/lab4/bonyuk_peter/test.mlir
> +    %7 = llvm.intr.fma(%4, %5, %6) : (f64, f64, f64) -> f64
Could you please add tests that has mul and add operations at input and fma on exit?

2024-05-21 01:52 UTC, m-ly4 commented on mlir/test/Transforms/lab4/bonyuk_peter/test.mlir
> +// CHECK: %6 = llvm.fmul %4, %5 : f64
Why your pass doesn't replace this case?

2024-05-22 15:03 UTC, aobolensk approved these changes

2024-05-22 15:31 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/bonyuk_peter/BonyukFusedMultiplyAddPass.cpp
> +    : public PassWrapper<BonyukFusedMultiplyAddPass, OperationPass<ModuleOp>> {
@PetrBonyuk Please apply this comment.

2024-05-25 10:32 UTC, PetrBonyuk commented
This Pass is intended for operations representing floating point addition (LLVM::FAddOp) and floating point multiplication (LLVM::FMulOp). This pass combines these operations into one combined multiply-add operation.

2024-05-30 16:47 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/bonyuk_peter/BonyukFusedMultiplyAddPass.cpp
> +    : public PassWrapper<BonyukFusedMultiplyAddPass, OperationPass<ModuleOp>> {
I meant to use FuncOp instead of ModuleOp.

2024-06-01 08:16 UTC, m-ly4 approved these changes

2024-06-01 08:17 UTC, merged