Shishkina Valeriya. Lab #1. Var #1.
NN-complr-tech/llvm-nnsu-2024 pull request #18
Opened 2024-03-16 19:37 UTC by ShLera04

As a result of the laboratory work, a plugin was written that outputs the names of all classes and their fields.

2024-03-17 08:25 UTC, m-ly4 commented on clang/labs/lab1/shishkina_valeriya/PrintClasses.cpp
> +    return true;
Please add a `help` argument and a test for it.

2024-03-17 08:29 UTC, m-ly4 requested changes

2024-03-17 08:29 UTC, m-ly4 commented on clang/labs/lab1/shishkina_valeriya/PrintClasses.cpp
> +class PrintClassesVisitor : public clang::RecursiveASTVisitor<PrintClassesVisitor> {
Please fix diff suggestions of clang-format test: https://github.com/NN-complr-tech/llvm-nnsu-2024/actions/runs/8310037939/job/22742071220?pr=18#step:4:14

2024-03-17 08:29 UTC, m-ly4 commented on clang/labs/lab1/shishkina_valeriya/PrintClasses.cpp
> +                 const std::vector<std::string> &args) override {
Could you please fix clang-tidy warnings if applicable: https://github.com/NN-complr-tech/llvm-nnsu-2024/actions/runs/8310037939/job/22742071140?pr=18#step:6:489

2024-03-18 17:43 UTC, m-ly4 commented on clang/test/lab1/shishkina_valeriya/tests.cpp
> +struct Test4{};
Please add a test for `help` argument.

2024-03-19 03:48 UTC, aobolensk approved these changes

2024-03-19 08:33 UTC, m-ly4 commented
@ShLera04 Arseniy have already approved the PR. But anyway could you please fix the test?

2024-03-19 14:14 UTC, m-ly4 approved these changes

2024-03-19 14:40 UTC, merged