Petrov Maksim. Lab 1. Var 3.
NN-complr-tech/llvm-nnsu-2024 pull request #19
Opened 2024-03-17 08:45 UTC by soileks

2024-03-17 12:49 UTC, m-ly4 requested changes

2024-03-17 12:49 UTC, m-ly4 commented on clang/labs/lab1/petrov_maksim/WarningDeprecatedPlugin.cpp
> +    return true;
Could you please add `help` argument and a test for it?

2024-03-17 12:49 UTC, m-ly4 commented on clang/labs/lab1/petrov_maksim/WarningDeprecatedPlugin.cpp
> +  explicit WarningDepricatedVisitor(ASTContext *Context) {this->Context = Context;}
Could you please pull last changes from main branch and fix clang-format and clang-tidy tests?

2024-03-17 17:44 UTC, soileks commented on clang/labs/lab1/petrov_maksim/WarningDeprecatedPlugin.cpp
> +  explicit WarningDepricatedVisitor(ASTContext *Context) {this->Context = Context;}
Clang-format and clang-tidy have been fixed and the "help" argument has been added.

2024-03-18 12:49 UTC, soileks commented on clang/labs/lab1/petrov_maksim/WarningDeprecatedPlugin.cpp
> +    for (unsigned i = 0, e = Args.size(); i != e; ++i) {
```suggestion
    for (unsigned I = 0, E = Args.size(); I != E; ++I) {
```

2024-03-18 13:05 UTC, soileks commented on clang/labs/lab1/petrov_maksim/CMakeLists.txt
> +set(CLANG_TEST_DEPS "WarningDeprecatedPlugin" ${CLANG_TEST_DEPS} PARENT_SCOPE)
```suggestion
set(CLANG_TEST_DEPS "WarningDeprecatedPlugin" ${CLANG_TEST_DEPS} PARENT_SCOPE)

```

2024-03-18 13:05 UTC, soileks commented on clang/test/lab1/petrov_maksim/tests.cpp
> +	void deprecatedFunc3() {}
```suggestion
  void deprecatedFunc3() {}
```

2024-03-18 13:34 UTC, soileks commented on clang/labs/lab1/petrov_maksim/WarningDeprecatedPlugin.cpp
> +      if (Args[i] == "help") {
```suggestion
      if (Args[I] == "help") {
```

2024-03-18 16:27 UTC, aobolensk approved these changes

2024-03-18 17:43 UTC, m-ly4 approved these changes

2024-03-18 17:47 UTC, merged