Иванов Никита ФИ3. Лабораторная работа № 1.
NN-complr-tech/llvm-nnsu-2024 pull request #2
Opened 2024-03-05 06:37 UTC by Atikin-NT

Реализован плагин, который кидает **warning**, если в названии функции встречается `deprecated`.

2024-03-07 06:04 UTC, m-ly4 commented on clang/test/lab1/ivanov_nikita/dep_matcher.cpp
> +// CHECK-NOT: warning: Deprecated in function name
```suggestion
// CHECK-NOT: warning: Deprecated in function name

```

2024-03-07 06:17 UTC, m-ly4 requested changes

2024-03-07 06:17 UTC, m-ly4 commented on clang/labs/lab1/ivanov_nikita/deprecatedMatcher.cpp
> +      return std::unique_ptr<ASTConsumer>(new DepConsumer(Compiler));
May we create `unique_ptr` without explicit `new` call here?

2024-03-07 06:17 UTC, m-ly4 commented on clang/test/lab1/ivanov_nikita/dep_matcher.cpp
> +// CHECK: warning: Deprecated in function name
Could you please add `help` argument check test?

2024-03-07 06:17 UTC, m-ly4 commented on clang/test/lab1/ivanov_nikita/dep_matcher.cpp
> +// CHECK: warning: Deprecated in function name
Could you please move `CHECK` lines closer to functions those checks belong to?

2024-03-07 06:17 UTC, m-ly4 commented on clang/labs/lab1/ivanov_nikita/deprecatedMatcher.cpp
> +    ros << "Help for DeprecatedPlugin plugin goes here\n";
Could you please write short but meaningful message here?

2024-03-07 06:17 UTC, m-ly4 commented on clang/labs/lab1/ivanov_nikita/CMakeLists.txt
> +# set(LLVM_LINK_COMPONENTS Support)
Please remove commented lines if you think they are not required.

2024-03-09 14:37 UTC, Atikin-NT commented
@m-ly4 I've done, you can check

2024-03-10 10:41 UTC, m-ly4 commented on clang/labs/lab1/ivanov_nikita/deprecatedMatcher.cpp
> +    explicit DepConsumer(CompilerInstance &CI): Instance(CI) {}
Overall, LGTM.
The last remark is: could you please align formatting of your files with the help of clang-format tool?

2024-03-10 17:37 UTC, m-ly4 approved these changes
Thank you.

2024-03-10 18:53 UTC, merged