Kazantsev Evgeny Lab 4 Var 3
NN-complr-tech/llvm-nnsu-2024 pull request #204
Opened 2024-05-26 12:55 UTC by neotouch1

2024-05-26 17:14 UTC, aobolensk requested changes

2024-05-26 17:14 UTC, aobolensk commented on mlir/test/Transforms/lab4/kazantsev_evgeny/test.mlir
> +// RUN: split-file %s %t
Come up with your own tests

2024-05-29 15:56 UTC, neotouch1 commented on mlir/test/Transforms/lab4/kazantsev_evgeny/test.mlir
> +// RUN: split-file %s %t
Added my own tests

2024-05-30 16:55 UTC, m-ly4 approved these changes

2024-06-01 09:19 UTC, m-ly4 requested changes

2024-06-01 09:19 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/kazantsev_evgeny/KazantsevPassDepthMax.cpp
> +  std::map<Operation *, int> Depth;
```suggestion
  llvm::DenseMap<Operation *, int> Depth;
```

2024-06-01 13:33 UTC, aobolensk approved these changes

2024-06-02 09:22 UTC, m-ly4 commented
@neotouch1 Could you please apply my remark and after that I'll merge your patch into master.

2024-10-17 18:47 UTC, m-ly4 approved these changes

2024-10-17 20:23 UTC, merged