Veselov Ilya. Lab 3. Option 2.
NN-complr-tech/llvm-nnsu-2024 pull request #205
Opened 2024-05-26 13:08 UTC by spells39

2024-05-27 12:01 UTC, m-ly4 requested changes

2024-05-27 12:01 UTC, m-ly4 commented on llvm/lib/Target/X86/lab3/veselov_ilya/X86VeselovIlyaCounterPass.cpp
> +    gVar->setInitializer(ConstantInt::get(Type::getInt64Ty(context), 0));
Are you sure that initializer should be set always unconditionally?

2024-05-27 12:01 UTC, m-ly4 commented on llvm/lib/Target/X86/lab3/veselov_ilya/X86VeselovIlyaCounterPass.cpp
> +          .addGlobalAddress(gVar, 0, X86II::MO_NO_FLAG)
Global variable contains an memory address actually, whilst `X86::ADD64ri32` expects register.

2024-05-29 15:21 UTC, aobolensk commented on llvm/test/lab3/veselov_ilya/test.mir
> +...
```suggestion
...

```

2024-06-01 09:31 UTC, m-ly4 approved these changes

2024-06-01 09:33 UTC, merged