Veselov Ilya. Lab 4. Option 4.
NN-complr-tech/llvm-nnsu-2024 pull request #207
Opened 2024-05-26 21:14 UTC by spells39

2024-05-27 14:30 UTC, aobolensk commented
It is lab 3, isn't it?

2024-05-27 14:53 UTC, spells39 commented
> It is lab 3, isn't it?

No, this is the fourth laboratory work. It's just that for some reason the third one got into this PR.

2024-05-27 14:55 UTC, aobolensk commented
> > It is lab 3, isn't it?
> 
> 
> 
> No, this is the fourth laboratory work. It's just that for some reason the third one got into this PR.

Please, remove it from this PR

2024-05-27 14:59 UTC, aobolensk requested changes

2024-05-27 14:59 UTC, aobolensk commented on mlir/lib/Transforms/lab4/veselov_ilya/VeselovIlyaCounterFuncCalls.cpp
> +      if (auto callOper = dyn_cast<LLVM::CallOp>(oper)) {
No need to use walker that walks through all operations and then filter. Walker can filter by itself

2024-05-27 14:59 UTC, aobolensk commented on mlir/test/Transforms/lab4/veselov_ilya/test.mlir
> +module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.d
```suggestion
module {
```

2024-05-27 14:59 UTC, aobolensk commented on mlir/test/Transforms/lab4/veselov_ilya/test.mlir
> +    // CHECK: countOfCalls = 2
Please match function name as a part of this check as well

2024-06-01 08:38 UTC, m-ly4 approved these changes

2024-06-01 08:50 UTC, merged