Kalnin Alexandr Lab1 Var 3
NN-complr-tech/llvm-nnsu-2024 pull request #212
Opened 2024-05-28 07:58 UTC by KalininA1

2024-05-28 11:10 UTC, aobolensk requested changes

2024-05-28 11:10 UTC, aobolensk commented on clang/labs/lab1/kalinin_alexandr/deprWarnPluginKalinin.cpp
> +  bool ParseArgs(const CompilerInstance &Compiler,
Please add an option for this pass to support both case sensitive and case insensitive match

2024-05-28 12:44 UTC, KalininA1 commented on clang/labs/lab1/kalinin_alexandr/deprWarnPluginKalinin.cpp
> +  bool ParseArgs(const CompilerInstance &Compiler,
Thanks, I've made the changes

2024-05-28 13:09 UTC, aobolensk commented on clang/labs/lab1/kalinin_alexandr/deprWarnPluginKalinin.cpp
> +  bool ParseArgs(const CompilerInstance &Compiler,
I think tests are still needed

2024-05-28 13:14 UTC, SSuren4ik commented on clang/labs/lab1/kalinin_alexandr/deprWarnPluginKalinin.cpp
> +  bool ParseArgs(const CompilerInstance &Compiler,
Sorry, but I have tests

2024-05-28 15:29 UTC, KalininA1 commented on clang/labs/lab1/kalinin_alexandr/deprWarnPluginKalinin.cpp
> +  bool ParseArgs(const CompilerInstance &Compiler,
@aobolensk 
Sorry, but I have tests. What did you mean?

2024-05-29 09:51 UTC, aobolensk commented on clang/labs/lab1/kalinin_alexandr/deprWarnPluginKalinin.cpp
> +  bool ParseArgs(const CompilerInstance &Compiler,
For both case sensitive and case insensitive

2024-05-29 17:21 UTC, KalininA1 commented on clang/labs/lab1/kalinin_alexandr/deprWarnPluginKalinin.cpp
> +  bool ParseArgs(const CompilerInstance &Compiler,
tests added

2024-05-30 15:06 UTC, aobolensk approved these changes

2024-05-30 16:59 UTC, merged