Kalinin Alexandr Lab 2 Var 3
NN-complr-tech/llvm-nnsu-2024 pull request #215
Opened 2024-05-28 15:37 UTC by KalininA1

2024-05-29 01:28 UTC, aobolensk requested changes

2024-05-29 01:28 UTC, aobolensk commented on llvm/labs/lab2/kalinin_alexandr/AddPass.cpp
> +                  if (Name == "loop_func") {
Please, use your surname as a part of plugin name as well

2024-05-29 01:28 UTC, aobolensk commented on llvm/test/lab2/kalinin_alexandr/tests.ll
> +; CHECK: call void @loop_start()
Can we check that they are inserted specifically in the beginning and at the end of the loop?

2024-05-29 10:46 UTC, KalininA1 commented on llvm/test/lab2/kalinin_alexandr/tests.ll
> +; CHECK: call void @loop_start()
Tests modified according to your instructions

2024-05-30 15:34 UTC, aobolensk approved these changes

2024-05-30 15:36 UTC, merged