Ivan check1
NN-complr-tech/llvm-nnsu-2024 pull request #22
Opened 2024-03-17 09:59 UTC by AdAndRoll

2024-03-17 10:00 UTC, AdAndRoll commented
test passed

2024-03-18 05:56 UTC, m-ly4 requested changes

2024-03-18 05:56 UTC, m-ly4 commented on clang/labs/lab1/vasilev_ivan/CMakeLists.txt
> +add_llvm_library(DeprecationPlugin MODULE Find_Deprication.cpp PLUGIN_TOOL clang)
```suggestion
add_llvm_library(DeprecationPlugin MODULE Find_Deprecation.cpp PLUGIN_TOOL clang)
```
Please fix this typo in all files names.

2024-03-18 05:56 UTC, m-ly4 commented on clang/labs/lab1/vasilev_ivan/Find_Deprication.cpp
> +    return true;
Could you please add an option that turns on search case insensitive `deprecated` substring in names?

2024-03-18 16:29 UTC, aobolensk commented
Please, fix: lab 1, variant 3

2024-03-19 05:32 UTC, m-ly4 approved these changes

2024-03-19 08:34 UTC, merged