Vyunov Danila. Lab 4. Option 2.
NN-complr-tech/llvm-nnsu-2024 pull request #230
Opened 2024-05-29 18:18 UTC by vyunolbek

2024-05-30 04:29 UTC, aobolensk requested changes

2024-05-30 04:29 UTC, aobolensk commented on mlir/test/Transforms/lab4/vyunov_danila/test.mlir
> +// RUN: mlir-opt -load-pass-plugin=%mlir_lib_dir/VyunovFMAPass%shlibext --pass-pipeline="builtin.module(llvm.func(VyunovFMAPass))" %s | FileCheck %s
Please, come up with your own tests

2024-05-30 04:29 UTC, aobolensk commented on mlir/lib/Transforms/lab4/vyunov_danila/VyunovFMAPass.cpp
> +          builder.create<mlir::math::FmaOp>(addOp.getLoc(), mulOp.getOperand(0),
Create llvm.intr.fma instead of math.fma

2024-05-30 04:29 UTC, aobolensk commented on mlir/lib/Transforms/lab4/vyunov_danila/VyunovFMAPass.cpp
> +      else if (auto mulOp = addRhs.getDefiningOp<mlir::LLVM::FMulOp>()) {
Add the check if both operands have been defined by fmul operations

2024-06-02 14:10 UTC, aobolensk commented
![image](https://github.com/NN-complr-tech/llvm-nnsu-2024/assets/31939330/7afdec95-c264-45cd-950f-c949b6c430af)
![image](https://github.com/NN-complr-tech/llvm-nnsu-2024/assets/31939330/e2fa96d5-13e5-4513-9ef8-56203f242c22)
You have submitted two empty commits, please consider fixing what was mentioned in the comments to proceed

2024-06-02 14:10 UTC, aobolensk requested changes
Please resolve comments

2024-06-02 14:20 UTC, vyunolbek commented
I accidentally made empty ones, I'll fix them now

2024-06-02 15:29 UTC, aobolensk approved these changes

2024-06-02 15:29 UTC, merged