Vetoshnikova Ekaterina Lab4 Var1
NN-complr-tech/llvm-nnsu-2024 pull request #231
Opened 2024-05-29 18:20 UTC by Veto1234-ii

2024-05-30 04:34 UTC, aobolensk requested changes

2024-05-30 04:34 UTC, aobolensk commented on mlir/lib/Transforms/lab4/vetoshnikova_ekaterina/convertToCeildiv.cpp
> +        loc, 1, builder.getIntegerType(32));
Please add tests for other integer sizes

2024-06-01 09:37 UTC, m-ly4 requested changes

2024-06-01 09:37 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/vetoshnikova_ekaterina/convertToCeildiv.cpp
> +        replaceCeildiv(ceilDivSI, true);
```
      if (isa<arith::CeilDivUIOp, arith::CeilDivSIOp>(op)) {
        replaceCeildiv(op);
```

2024-06-01 09:37 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/vetoshnikova_ekaterina/convertToCeildiv.cpp
> +  void replaceCeildiv(Operation *op, bool isSigned) {
Please implement this function without additional argument `isSigned`.

2024-06-01 13:39 UTC, aobolensk approved these changes

2024-06-02 15:49 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/vetoshnikova_ekaterina/convertToCeildiv.cpp
> +    if (sub.getType().isSignlessInteger() && b.getType().isSignlessInteger()) {
Ok, this check is appropriate.
Bit you could do the same:
```
if (isa<arith::CeilDivSIOp>(op)) {
```

2024-06-02 15:50 UTC, m-ly4 approved these changes

2024-06-02 23:35 UTC, merged