Ulyanov Daniil Lab4 Var4
NN-complr-tech/llvm-nnsu-2024 pull request #242
Opened 2024-05-30 20:46 UTC by UlyanovDaniil

2024-06-01 09:44 UTC, m-ly4 requested changes

2024-06-01 09:44 UTC, m-ly4 commented on mlir/lib/Transforms/lab4/ulyanov_daniil/file.cpp
> +    std::vector<LLVM::LLVMFuncOp> funcs;
Please make this function without use of a container for functions.

2024-06-01 09:44 UTC, m-ly4 commented on mlir/test/Transforms/lab4/ulyanov_daniil/tests.mlir
> +module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<!llvm.ptr<270>, dense<32> : vector<4xi32>>, #dlti.dl_entry<!llvm.ptr<272>, dense<64> : vector<4xi32>>, #dlti.dl_entry<!llvm.ptr<271>, de
```suggestion
module {
```

2024-06-01 09:44 UTC, m-ly4 commented on mlir/test/Transforms/lab4/ulyanov_daniil/tests.mlir
> +  llvm.func @_Z5func2v() -> (i32 {llvm.noundef}) attributes {passthrough = ["mustprogress", "noinline", "nounwind", "optnone", ["uwtable", "2"], ["frame-pointer", "all"], ["min-legal-vector-width", "
Please add a case for `func.func` function from `func` dialect.

2024-06-02 00:37 UTC, aobolensk approved these changes

2024-06-02 08:42 UTC, m-ly4 approved these changes

2024-06-02 08:42 UTC, merged