Balyasov Ivan. Lab 2 - var 4 (new branch)
NN-complr-tech/llvm-nnsu-2024 pull request #272
Opened 2024-09-29 09:35 UTC by DiPirs

The git folder broke on the computer, I had to make a new branch, because I couldn't get access to the old branch back. Added an additional task from Pull requests #75 - [link](https://github.com/NN-complr-tech/llvm-nnsu-2024/pull/75)

2024-10-16 00:20 UTC, aobolensk requested changes

2024-10-16 00:20 UTC, aobolensk commented on llvm/labs/lab2/balyasov_ivan/mul_to_bit_shift.cpp
> +  int getLogBase2(llvm::Value *val) {
Please use std::optional to get rid of negative values here (-2)

2024-10-17 05:32 UTC, m-ly4 commented on llvm/test/lab2/balyasov_ivan/test.ll
> +
Could you please also add test for case:

int f9(int a) {
    return a × 8;
}

2024-10-18 05:46 UTC, aobolensk approved these changes

2024-10-18 05:46 UTC, merged