Loginov Maxim Lab1 Var4
NN-complr-tech/llvm-nnsu-2024 pull request #275
Opened 2024-09-29 16:44 UTC by MaximkaLoginov

2024-10-16 00:30 UTC, aobolensk requested changes

2024-10-16 00:30 UTC, aobolensk commented on clang/test/lab1/loginov_maxim/test.cpp
> +    int a;
Add check for static class members

2024-10-18 11:37 UTC, m-ly4 approved these changes

2024-10-18 14:57 UTC, aobolensk approved these changes

2024-10-18 14:57 UTC, merged