Mirzakhmedov Alexander Lab1 Var1
NN-complr-tech/llvm-nnsu-2024 pull request #288
Opened 2024-10-05 19:30 UTC by OGGLucky

В лабораторной работе необходимо напечатать имена всех классов и их поля в виде:
MyClass
  |_ a
  |_ b

2024-10-16 00:57 UTC, aobolensk requested changes

2024-10-16 00:57 UTC, aobolensk commented on clang/test/lab1/mirzakhmedov_alexander/mirzakhmedovClassesTests.cpp
> +
Please add your own tests

2024-10-17 09:31 UTC, OGGLucky commented on clang/test/lab1/mirzakhmedov_alexander/mirzakhmedovClassesTests.cpp
> +
Done

2024-10-17 13:39 UTC, aobolensk approved these changes

2024-10-17 13:39 UTC, merged