Sharapov Georgiy. First Lab.
NN-complr-tech/llvm-nnsu-2024 pull request #3
Opened 2024-03-10 03:48 UTC by nol0n

Added plugin that emits a warning for each function that has the `[[deprecated]]` attribute.

2024-03-11 12:44 UTC, m-ly4 requested changes

2024-03-11 12:44 UTC, m-ly4 commented on clang/labs/lab1/sharapov_georgiy/DepWarningPlugin.cpp
> + public:
Could you please align your code with the help of `clang-format` tool?

2024-03-11 12:44 UTC, m-ly4 commented on clang/test/lab1/sharapov_georgiy/test.cpp
> +void newSum(int a, int b) {}
Could you please check that there is no `deprecated` warning?

2024-03-11 12:44 UTC, m-ly4 commented on clang/labs/lab1/sharapov_georgiy/DepWarningPlugin.cpp
> +        if (F->hasAttr<clang::DeprecatedAttr>()) {
Could you please also cover gcc-style `deprecated` attribute?

2024-03-11 12:44 UTC, m-ly4 commented on clang/labs/lab1/sharapov_georgiy/DepWarningPlugin.cpp
> +        return true;
Could you please add `attr-style` argument specifying which style of `deprecated` attribute to cover? Options may be `[c++14, gcc, both]`.
Please also add tests for these arguments.

2024-03-14 05:11 UTC, m-ly4 requested changes

2024-03-14 05:11 UTC, m-ly4 commented on clang/test/lab1/sharapov_georgiy/test.cpp
> +void Func(int a, int b);
```suggestion
void Func(int a, int b);

```

2024-03-14 05:11 UTC, m-ly4 commented on clang/labs/lab1/sharapov_georgiy/DepWarningPlugin.cpp
> +          llvm::outs() << "\n  Invalid value for attr-style. Using default "
Could you please report unexpected option parameter warning via diagnostic?
And also check it in a test?

2024-03-14 15:07 UTC, nol0n commented
@m-ly4, could you please take a look at the windows-build? This commit in my fork passed tests without issues ([link to the test results](https://github.com/nol0n/llvm-nnsu-2024/actions/runs/8276739737/job/22645817184)) and as far as I can tell, the problem doesn't seem to be with my code. However, I might be mistaken.

2024-03-14 20:12 UTC, m-ly4 commented
> @m-ly4, could you please take a look at the windows-build? This commit in my fork passed tests without issues ([link to the test results](https://github.com/nol0n/llvm-nnsu-2024/actions/runs/8276739737/job/22645817184)) and as far as I can tell, the problem doesn't seem to be with my code. However, I might be mistaken.

Looks like it was just infrastructure problem. I restarted windows test.

2024-03-14 20:13 UTC, m-ly4 approved these changes

2024-03-15 00:33 UTC, aobolensk commented
LGTM

2024-03-15 00:34 UTC, aobolensk approved these changes

2024-03-15 00:34 UTC, merged