Ryabkov Vladislav Lab3 Var1
NN-complr-tech/llvm-nnsu-2024 pull request #304
Opened 2024-10-15 17:35 UTC by AgentV0

It is necessary to write an optimization pass that replaces multiplication and addition operation

2024-10-16 01:23 UTC, aobolensk requested changes

2024-10-16 01:23 UTC, aobolensk commented on llvm/test/lab3/ryabkov_vladislav/test.mir
> +#
Please, add test for (a + b) * c

2024-10-16 22:33 UTC, AgentV0 commented on llvm/test/lab3/ryabkov_vladislav/test.mir
> +#
done

2024-10-18 05:50 UTC, aobolensk approved these changes

2024-10-18 05:51 UTC, merged