Akopyan Zal. Lab 1. Var 2.
NN-complr-tech/llvm-nnsu-2024 pull request #44
Opened 2024-03-19 17:59 UTC by akopyanzal

I made plugin that adds the inline attribute

2024-03-19 18:24 UTC, m-ly4 requested changes

2024-03-19 18:24 UTC, m-ly4 commented on clang/test/lab1/akopyan_zal/Test.cpp
> +// CHECK: __attribute__((always_inline)) FuncInline
Please check attribute presence in AST tree.

2024-03-19 18:24 UTC, m-ly4 commented on clang/test/lab1/akopyan_zal/Test.cpp
> +
Please check that attribute is absent in the following example
```suggestion
void FuncNotInline() {
  {
  if (true) {
    return;
  }
}
  return;
}
```

2024-03-19 18:24 UTC, akopyanzal commented
Why my tests are not running?

2024-03-22 16:34 UTC, m-ly4 commented on clang/labs/lab1/akopyan_zal/AlwaysInline.cpp
> +    X("always-inline", "Plugin that adds the inline attribute");
Try to change dash in plugin name on underscore:
```suggestion
    X("always_inline", "Plugin that adds the inline attribute");
```

2024-03-24 09:49 UTC, m-ly4 requested changes

2024-03-24 09:49 UTC, m-ly4 commented on clang/test/lab1/akopyan_zal/Test.cpp
> +// RUN: %clang_cc1 -ast-dump -ast-dump-filter -load %llvmshlibdir/AlwaysInlinePluginAkopyan%pluginext -plugin always-inline %s 2>&1 | FileCheck %s
Here name should be changed too:
```suggestion
// RUN: %clang_cc1 -ast-dump -ast-dump-filter -load %llvmshlibdir/AlwaysInlinePluginAkopyan%pluginext -plugin always_inline %s 2>&1 | FileCheck %s
```

2024-03-24 18:31 UTC, akopyanzal commented on clang/test/lab1/akopyan_zal/Test.cpp
> +// RUN: %clang_cc1 -ast-dump -ast-dump-filter -load %llvmshlibdir/AlwaysInlinePluginAkopyan%pluginext -plugin always-inline %s 2>&1 | FileCheck %s
done

2024-03-30 19:32 UTC, m-ly4 commented
If you have any questions regarding this lab you may come to practice and ask them.

2024-04-02 15:37 UTC, m-ly4 requested changes

2024-04-02 15:37 UTC, m-ly4 commented on clang/labs/lab1/akopyan_zal/AlwaysInline.cpp
> +                       << func->getNameAsString() << "\n";
```suggestion
```

2024-05-18 15:25 UTC, m-ly4 requested changes

2024-05-18 15:25 UTC, m-ly4 commented on clang/test/lab1/akopyan_zal/Test.cpp
> +}
What about other statements (loops, switch)?

2024-05-25 14:16 UTC, m-ly4 approved these changes

2024-05-25 14:17 UTC, merged