Kruglov Alexey. Lab 1. Var 4.
NN-complr-tech/llvm-nnsu-2024 pull request #46
Opened 2024-03-19 18:53 UTC by KrYackI

Plugin that renames units(variables, functions, classes) with entered identificator to another entered identificator.

2024-03-20 15:58 UTC, m-ly4 commented on clang/labs/lab1/kruglov_alexey/RenameID.cpp
> +      Rewriter.overwriteChangedFiles();
May we do this overwrite less frequently?

2024-03-20 16:00 UTC, m-ly4 commented on clang/labs/lab1/kruglov_alexey/RenameID.cpp
> +    if (args[0].find("OldName=") == std::string::npos || args[1].find("NewName=") == std::string::npos){
What if a user passes `SomeOldName` argument?

2024-03-20 16:03 UTC, m-ly4 requested changes
Please fix clang-format and clang-tidy remarks if applicable.

2024-03-24 08:06 UTC, aobolensk requested changes

2024-03-24 08:06 UTC, aobolensk commented on clang/labs/lab1/kruglov_alexey/RenameID.cpp
> +        Func->getReturnType().getAsString() == OldName + " &") {
This code is repeated several times across this class. Please, extract it to the separate function

2024-03-24 18:04 UTC, aobolensk approved these changes

2024-03-24 19:02 UTC, m-ly4 approved these changes

2024-03-24 19:02 UTC, merged