Ivanov Nikita. Lab 2. Var 3.
NN-complr-tech/llvm-nnsu-2024 pull request #61
Opened 2024-03-29 18:32 UTC by Atikin-NT

Реализован плагин и тесты по задаче 

> _Найти все циклы внутри функции и обернуть их в вызовы loop_start()/loop_end(). Можно использовать Loop Analysis._.

2024-03-30 20:10 UTC, m-ly4 requested changes

2024-03-30 20:10 UTC, m-ly4 commented on llvm/test/lab2/ivanov_nikita/test.ll
> +;     for (c0 = n; c0 > 0; c0--) {
Could you please add the following test cases:
- while, do-while loops
- no loops but if-else condition present (check that no insertion is done)
- function with any loop and already added `loop_*` calls

2024-03-30 20:10 UTC, m-ly4 commented on llvm/labs/lab2/ivanov_nikita/ivanov.cpp
> +      if (!Preheader)
I'd suggest firstly perform all checks and if all is fine then insert `loop_*` calls.

2024-03-30 20:10 UTC, m-ly4 commented on llvm/labs/lab2/ivanov_nikita/CMakeLists.txt
> +
```suggestion
```

2024-03-31 14:48 UTC, m-ly4 requested changes

2024-03-31 14:48 UTC, m-ly4 commented on llvm/test/lab2/ivanov_nikita/test.ll
> +; RUN: opt -passes=ivanov-loop-pass -S %s 2>&1 | FileCheck %s
Could you please load plugin as dynamic library at runtime?

2024-04-01 06:23 UTC, Atikin-NT commented
@m-ly4 I've done, you can check

2024-04-01 14:08 UTC, m-ly4 commented on llvm/test/lab2/ivanov_nikita/test.ll
> +
```suggestion
void LoopWithRet(int &a) {
  int i = 0;
  while(i < 100){
         i++;
         if (i > 10) {
            return;
         }
         a = a + i;
     }
     a *= i -1;
     return;
}

```

2024-04-01 14:09 UTC, m-ly4 commented on llvm/test/lab2/ivanov_nikita/test.ll
> +  br label %while.cond
```suggestion
; CHECK-NOT: loop_start
  br label %while.cond
```

2024-04-01 19:11 UTC, m-ly4 approved these changes

2024-04-02 13:59 UTC, merged