Soloninko Andrey. Lab 2, opt. 1
NN-complr-tech/llvm-nnsu-2024 pull request #63
Opened 2024-03-29 20:58 UTC by Manymoera

Inserts `instrument_start()` and `instrument_end()` functions into the begining and end of every function in a module.
Example: 
`void func() {}`
will be turned into
`void func() { instrument_start(); instrument_end(); }`

2024-03-30 20:35 UTC, m-ly4 requested changes

2024-03-30 20:35 UTC, m-ly4 commented on llvm/labs/lab2/soloninko_andrey/instrumentation.cpp
> +        if (auto *callInst = llvm::dyn_cast<llvm::CallInst>(&I)) {
In generic case it is more performant to just check that `F` is not present among users of `func_f` and `func_l` functions.

2024-03-31 09:30 UTC, Manymoera commented
@m-ly4 I have changed my method of finding function calls. Now it searches for `F` to be present among users of `func_l` and `func_f` functions.

2024-03-31 11:39 UTC, m-ly4 requested changes

2024-03-31 11:39 UTC, m-ly4 commented on llvm/test/lab2/soloninko_andrey/foo.ll
> +; CHECK: call void @instrument_end()
```suggestion
; CHECK-NEXT: call void @instrument_end()
```

2024-03-31 11:39 UTC, m-ly4 commented on llvm/test/lab2/soloninko_andrey/foo.ll
> +; CHECL-NEXT: %a.addr = alloca i32, align 4
```suggestion
; CHECK-NEXT: %a.addr = alloca i32, align 4
```

2024-03-31 11:39 UTC, m-ly4 commented on llvm/test/lab2/soloninko_andrey/foo.ll
> +; CHECL-NEXT: %a.addr = alloca i32, align 4
```suggestion
; CHECK-NEXT: %a.addr = alloca i32, align 4
```

2024-03-31 11:39 UTC, m-ly4 commented on llvm/test/lab2/soloninko_andrey/foo.ll
> +; CHECK: call void @instrument_end()
```suggestion
; CHECK-NEXT: call void @instrument_end()
```

2024-03-31 11:39 UTC, m-ly4 commented on llvm/test/lab2/soloninko_andrey/foo.ll
> +; CHECL-NEXT: %a.addr = alloca i32, align 4
```suggestion
; CHECK-NEXT: %a.addr = alloca i32, align 4
```

2024-03-31 18:58 UTC, m-ly4 approved these changes

2024-03-31 18:59 UTC, merged