Balyasov Ivan. Lab 2 - var 4.
NN-complr-tech/llvm-nnsu-2024 pull request #75
Opened 2024-04-01 19:49 UTC by DiPirs

Plugin that replaces integer multiplication to bit shift, if it is possible

2024-04-02 14:41 UTC, m-ly4 requested changes

2024-04-02 14:41 UTC, m-ly4 commented on llvm/test/lab2/balyasov_ivan/test.ll
> +
Could you please also test the following case:

```
;void f7(){
;    int a = 4;
;    int c = a * 3;
;}

; CHECK-LABEL: @f7
; CHECK: %3 = load i32, ptr %1, align 4
; CHECK-NEXT: %4 = shl i32 3, 2
; CHECK-NEXT: store i32 %4, ptr %2, align 4
```

2024-04-02 17:18 UTC, DiPirs commented
Why is ubuntu-gcc-build not working at the build stage? All tests were completed in the afternoon...

2024-04-03 19:37 UTC, m-ly4 requested changes

2024-04-03 19:37 UTC, m-ly4 commented on llvm/labs/lab2/balyasov_ivan/CMakeLists.txt
> +  ${ALL_SOURCE_FILES}     )
```suggestion
  ${ALL_SOURCE_FILES}
  DEPENDS intrinsics_gen BUILDTREE_ONLY)
```

2024-04-03 19:37 UTC, m-ly4 commented on llvm/test/lab2/balyasov_ivan/test.ll
> +; CHECK-NEXT: %4 = mul nsw i32 %3, 3
I'd expect the following:
```suggestion
; CHECK-NEXT: %4 = shl i32 3, 2
```

2024-10-17 05:33 UTC, closed without merging