Polozov Vladislav Lab 2. Var 3.
NN-complr-tech/llvm-nnsu-2024 pull request #78
Opened 2024-04-02 00:00 UTC by Mortus19

Написал плагин, который добавляет функции loop_start() в начало цикла , и loop_end() в конец цикла

2024-04-02 15:17 UTC, m-ly4 requested changes

2024-04-02 15:17 UTC, m-ly4 commented on llvm/labs/lab2/polozov_vladislav/CMakeLists.txt
> +    add_llvm_pass_plugin(LoopPass LoopPass.cpp)
Please add longer name incl. your surname.

2024-04-02 15:17 UTC, m-ly4 commented on llvm/labs/lab2/polozov_vladislav/LoopPass.cpp
> +      if (isCalled(BB, loopEnd) == false) {
```suggestion
      if (!isCalled(BB, loopEnd)) {
```

2024-04-02 15:17 UTC, m-ly4 commented on llvm/labs/lab2/polozov_vladislav/LoopPass.cpp
> +      if (L->contains(Pred) == false && isCalled(Pred, loopStart) == false) {
```suggestion
      if (!L->contains(Pred) && !isCalled(Pred, loopStart)) {
```

2024-04-02 15:17 UTC, m-ly4 commented on llvm/labs/lab2/polozov_vladislav/LoopPass.cpp
> +    return called;
```suggestion
    for (auto &inst : *BB)
      if (auto *instCall = llvm::dyn_cast<llvm::CallInst>(&inst))
        if (instCall->getCalledFunction() == callee.getCallee())
          return true;
    return false;
```

2024-04-02 15:17 UTC, m-ly4 commented on llvm/test/lab2/polozov_vladislav/test.ll
> +
Please also check that loop_start/loop_end declarations added.

2024-04-02 15:17 UTC, m-ly4 commented on llvm/test/lab2/polozov_vladislav/test.ll
> +;int main(){
Please add a test for a loop with already inserted loop_start/loop_end instructions.

2024-04-02 15:17 UTC, m-ly4 commented on llvm/labs/lab2/polozov_vladislav/LoopPass.cpp
> +    PA.abandon<llvm::LoopAnalysis>();
Is it necessary?

2024-04-02 19:19 UTC, Mortus19 commented
@m-ly4 Внес поправки, но Ubuntu-gcc-build упал, видимо из-за чужих файлов. Хотя раньше все проходило, я просто поменял название библиотеки в CMake. Можете, пожалуйста, посмотреть что случилось

2024-04-02 19:28 UTC, m-ly4 commented
> @m-ly4 Внес поправки, но Ubuntu-gcc-build упал, видимо из-за чужих файлов. Хотя раньше все проходило, я просто поменял название библиотеки в CMake. Можете, пожалуйста, посмотреть что случилось 

Да, сейчас смотрю, в чем дело.

2024-04-03 14:50 UTC, m-ly4 approved these changes

2024-04-03 14:50 UTC, merged