Korablev Nikita. Lab №1. Option №4.
NN-complr-tech/llvm-nnsu-2024 pull request #8
Opened 2024-03-13 20:49 UTC by NikitaKorablev

A plugin has been implemented that renames identifiers (variable name, class name, function name).
Example:
```c++
class A {
public:
    A() {};
    ~A();
};
void func() {
    A* a = new A;
    A b;
    delete a;
};
```
Result:
```c++
class B {
public:
    B() {};
    ~B();
};
void func() {
    B* a = new B;
    B b;
    delete a;
 };
```

2024-03-15 00:39 UTC, aobolensk requested changes

2024-03-15 00:39 UTC, aobolensk commented on clang/labs/lab1/korablev_nikita/RenameIdentificator.cpp
> +using namespace clang::transformer;
Please, avoid using "using namespace *". "Using" statement for particular namespace members is ok (like ast_matchers and transformer)

2024-03-15 00:39 UTC, aobolensk commented on clang/labs/lab1/korablev_nikita/RenameIdentificator.cpp
> +        }
It looks like these two ifs can be merged

2024-03-15 16:14 UTC, m-ly4 commented
Could you please align code with a help of clang-format tool?
And also fix warnings printed by https://github.com/NN-complr-tech/llvm-nnsu-2024/actions/runs/8294689254/job/22700181439?pr=8

2024-03-15 18:09 UTC, aobolensk commented
Please, update the branch to go through updated clang-format check

2024-03-17 07:43 UTC, m-ly4 approved these changes

2024-03-18 05:31 UTC, aobolensk approved these changes

2024-03-18 05:31 UTC, merged