Pushkarev Ilya \ Lab2 \ Var 2
NN-complr-tech/llvm-nnsu-2024 pull request #88
Opened 2024-04-03 18:34 UTC by oleg212

2024-04-14 19:10 UTC, oleg212 commented
some more tests are to be added

2024-04-16 15:08 UTC, oleg212 commented
done

2024-04-23 18:42 UTC, m-ly4 requested changes

2024-04-23 18:42 UTC, m-ly4 commented on llvm/labs/lab2/pushkarev_ilya/InlineFunc.cpp
> +        llvm::CallInst *callInst = llvm::dyn_cast<llvm::CallInst>(&instruction);
```suggestion
        auto *callInst = llvm::dyn_cast<llvm::CallInst>(&instruction);
```

2024-04-23 18:42 UTC, m-ly4 commented on llvm/labs/lab2/pushkarev_ilya/InlineFunc.cpp
> +            llvm::BasicBlock *currentBlock = blockMap[&inlinedBlock];
```suggestion
          llvm::BasicBlock *currentBlock = blockMap[&inlinedBlock];
          for (llvm::Instruction &inlinedInstruction : inlinedBlock) {
```

2024-04-23 18:42 UTC, m-ly4 commented on llvm/labs/lab2/pushkarev_ilya/InlineFunc.cpp
> +                                   operand)]));
```suggestion
                  if (auto *bb = llvm::dyn_cast<llvm::BasicBlock>(*operand)) {
                    newInstruction->setOperand(
                        i, llvm::dyn_cast<llvm::Value>(blockMap[bb]));
```

2024-04-23 18:42 UTC, m-ly4 commented on llvm/test/lab2/pushkarev_ilya/test.ll
> +  call void @_Z11void_no_argv()
Could you please add a test where both functions have a loop or if statement?

2024-04-26 20:20 UTC, m-ly4 approved these changes

2024-04-26 20:20 UTC, merged